### ISSUE TITLE
#each and await promise 

### ISSUE THREAD

**Issue by Techn1x** [fivetanley/ember-promise-helpers#21]
Hi there, thanks for the handy addon.

I noticed on the readme page, there is an example like this

```handlebars
{{#each (await model.comments) as |comment|}}
  {{comment.author}} wrote {{comment.text}}
{{/each}}
```

I've got some code that looks like this
```handlebars
{{#each (await images) as |imgCap i|}}
  {{log imgCap}}
{{/each}}
```

Unfortunately it seems that imgCap is still a promise? Is this how it's supposed to work? From the example, I would have thought imgCap would be set to the object after the promise fulfillment thanks to `await`

If I use `{{log (await imgCap)}}` it works fine but this adds a lot of complication to my code...

**Comment by fivetanley** [comment]
What is `images`? Is this an array of promises?

**Comment by Techn1x** [comment]
Yeah, an array of promises.

I can see how I got confused now, `{{#each (await model.comments) as |comment|}}` works because `model.comments` is a singular promise to an array of records. But I was trying to use it in the opposite way, supplying an array of promises.

Is this something this helper could support?

**Comment by abobwhite** [comment]
@Techn1x Maybe https://github.com/fivetanley/ember-promise-helpers#promise-all ?

**Comment by Techn1x** [comment]
hmmm that could potentially work. Assuming it works with the #each helper, I'll give it a go when I get a chance.
Something like
```handlebars
{{#each (promise-all imagesPromiseArray) as |imgCap i|}}
    {{log imgCap}}
{{/each}}
```

**Comment by fivetanley** [comment]
Promise-all should meet this use case. Feel free to reopen if not!

**Comment by Techn1x** [comment]
Sorry I never got back to this issue - I ended up refactoring some code and avoiding the need for this altogether.

But I'll be on the lookout in my code for any other places I can use this :)
