### ISSUE TITLE
is-rejected does not work

### ISSUE THREAD

**Issue by nezmen** [fivetanley/ember-promise-helpers#35]
`{{#if promise.isRejected}}` does not trigger on 404 errors

The promise is from the following:
`  promise: Ember.computed('', function()
  {
    return DS.PromiseObject.create(
    {
      promise: Ember.$.getJSON(`/api/someRoute`)
    });
  }),`

Doing this works:
`{{#if promise.isRejected}}`

**Comment by fivetanley** [comment]
Do jQuery promises reject on 404s? Also what version of jQuery are you using?

**Comment by nezmen** [comment]
2.1.4 

```
Ember.$.getJSON('/api/things/99999/')

returns

{readyState: 1, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
abort: ƒ (t)
always: ƒ ()
complete: ƒ ()
done: ƒ ()
error: ƒ ()
fail: ƒ ()
getAllResponseHeaders: ƒ ()
getResponseHeader: ƒ (t)
overrideMimeType: ƒ (t)
pipe: ƒ ()
progress: ƒ ()
promise: ƒ (t)
readyState: 4
responseJSON: {message: "No HTTP resource was found that matches the request URI 'http://myDomain/api/things/99999/'.", messageDetail: "No type was found that matches the controller named 'things'."}
responseText: "{"message":"No HTTP resource was found that matches the request URI 'http://myDomain/api/things/99999/'.","messageDetail":"No type was found that matches the controller named 'things'."}"
setRequestHeader: ƒ (t,e)
state: ƒ ()
status: 404
statusCode: ƒ (t)
statusText: "Not Found"
success: ƒ ()
then: ƒ ()
__proto__: Object
```

**Comment by fivetanley** [comment]
Hey @nezmen ,

jquery 2 uses "promises" but they are not really [A+ promises](https://promisesaplus.com/) (the promise spec that the browser, node, and RSVP (ember's promise library) all implement). In addition, I think DS.PromiseObject is a private api and not actually required for the promise helpers to work.

jQuery 3 has A+ compliant promises, you may want to try upgrading. Supporting jquery 2 promises and a private ember data API isn't something I have time to take on at the moment, sorry. :(
