### ISSUE TITLE
{{is-pending}} on array helper array causes infinite rendering invalidation

### ISSUE THREAD

**Issue by benedikt** [fivetanley/ember-promise-helpers#59]
I'm using `{{is-pending}}` and `{{await}}` to handle promises passed to a component. It works great for both promises and regular values. Unfortunately, passing an array generated using Ember's `{{array "..."}}` helper causes an `infinite rendering invalidation` error.

Here's an [Ember Twiddle](https://ember-twiddle.com/d2c2ad5ad46e569f9dc266abf045f089?openFiles=templates.application%5C.hbs%2C) that reproduces the problem in a minimal setup. 

I'm happy to help fixing this issue, but I'm a bit lost on the root cause of this. Do you have any pointers?

**Comment by fivetanley** [comment]
Hi,

Sorry this error happened. That's pretty frustrating and opaque to debug.

If you're using an array, you might want to use the `promise-all` helper to wrap that value. I made a fork of your twiddle here to show that: https://ember-twiddle.com/1761e2e33c7c85bce10d80d74cd3d98b?openFiles=templates.application%5C.hbs%2C

Here's the new code for posterity:

Before:

```handlebars
Array, is pending: {{is-pending (array "one" "two" "three")}}
```

After:

```handlebars
Array, is pending: {{is-pending (promise-all (array "one" "two" "three"))}}
```

I would happily accept a PR to the `is-*` helpers that use `Ember.assert` to throw an exception to guide folks using this library to use `promise-all` or `promise-map` to wrap values before passing them to `is-pending`.

**Comment by benedikt** [comment]
Thanks for the suggestion to wrap the collection in a `promise-all` helper. That makes more sense than wrapping it in `await`.
